name: generate-cred

on:
  # Trigger on merging to master.
  push:
    branches:
      - master
  # As well as every hour.
  schedule:
    # Every Sunday at 29:59
    - cron: 59 23 * * 0
    # Every 5 min
    # - cron: 0-59/5 * * * *
    # Every 30 min
    # - cron: 30 * * * *
    # Every hour
    # - cron: 0 */1 * * *

jobs:
  GenerateCred:
    name: Generate Cred
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      # - name: SourceCred Cache
      #   uses: actions/cache@v1
      #   with:
      #     # cred-action uses *workspace*/sourcecred_data as it's SOURCECRED_DIRECTORY. Only store the cache from that.
      #     path: sourcecred_data/cache
      #     key: SC_CACHE-${{ hashFiles('**/collective.json') }}-${{ github.run_id }}
      #     restore-keys: |
      #       SC_CACHE-${{ hashFiles('**/collective.json') }}-
      #       SC_CACHE-
      - name: Run SourceCred
        # uses: vsoch/cred-action@wip-discord-cache
        uses: vsoch/cred-action@master
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          # SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}
        with:
          weights: weights.json
          project: "@ocean-collective"
          project-file: projects/collective.json
          # branch-against: master
          automated: true
          # test-run: true
